development: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  port: 3306
  pool: 5
  database: <%= ENV['DB_NAME']%>
  host: <%= ENV['DB_HOST']%>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>

test:
  <<: *base
